### ISSUE TITLE
What is the value of '{model}' in openapi.yaml defined to be

### ISSUE THREAD

**Issue by hmlanigan** [jnsgruk/juju-api#6]
In some of the endpoints, there is a '{model}', but I'm unable to find what its value should be.  I am unable to find the definition so far? 

While working on the juju terraform provider, it quickly became apparent that for all clients, referring to a model by UUID is problematic. Either you must cache the name to UUID mapping, or make an extra request to find the value every time. The juju client caches the value. However, name and UUID are immutable once the model has been created. We have no rename model functionality today. The terraform plans for the juju provider refer to models by name, forcing a lookup to make calls. 

We should consider defining the value of '{model}' to be the model name if it's not already.

**Comment by jnsgruk** [comment]
👋 

My intention so far has been that {model} is the model name, so I think we should be safe!
